# Generated by Django 5.2 on 2025-04-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcela',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
