# Generated by Django 5.2 on 2025-05-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcela',
            name='aplicar_incc',
            field=models.BooleanField(default=True),
        ),
    ]
