# Generated by Django 5.2 on 2025-04-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_parcela_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcela',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
