# Generated by Django 5.2 on 2025-05-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_parcela_aplicar_incc'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcela',
            name='aplicar_juros',
            field=models.BooleanField(default=True),
        ),
    ]
