# Generated by Django 5.2 on 2025-05-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_parcela_aplicar_juros'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcela',
            name='aplicar_multa',
            field=models.BooleanField(default=True),
        ),
    ]
