# Generated by Django 5.2 on 2025-04-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_parcela_nome'),
    ]

    operations = [
        migrations.DeleteModel(
            name='INCCIndex',
        ),
        migrations.AddField(
            model_name='parcela',
            name='percentual_incc',
            field=models.FloatField(blank=True, help_text='Percentual do INCC aplicado na parcela', null=True),
        ),
    ]
