# Generated by Django 5.2 on 2026-04-07 18:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_configuracaocalculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaocalculo',
            name='juros_percentual_mensal',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0100'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='configuracaocalculo',
            name='multa_percentual',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0200'), max_digits=5),
        ),
    ]
